name: aromatizador
description: "App simples Olá Mundo"
publish_to: 'none'

version: 1.2.3+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
